# Generated by Django 2.0.3 on 2019-07-13 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('env_id', models.AutoField(primary_key=True, serialize=False)),
                ('env_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=100)),
                ('is_swagger', models.IntegerField(default='')),
                ('set_headers', models.TextField(default='')),
                ('private_key', models.CharField(max_length=100)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('if_id', models.AutoField(primary_key=True, serialize=False)),
                ('if_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('data_type', models.CharField(max_length=10)),
                ('is_sign', models.IntegerField()),
                ('is_header', models.IntegerField(default='')),
                ('set_mock', models.TextField(default='')),
                ('description', models.CharField(max_length=200)),
                ('request_header_param', models.TextField()),
                ('request_body_param', models.TextField()),
                ('response_header_param', models.TextField()),
                ('response_body_param', models.TextField()),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('report_name', models.CharField(default='', max_length=255)),
                ('make', models.IntegerField(null=True)),
                ('is_locust', models.IntegerField(default='')),
                ('is_task', models.IntegerField(default='')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.CharField(default='', max_length=30)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('prj_id', models.AutoField(primary_key=True, serialize=False)),
                ('prj_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=255)),
                ('pic_name', models.CharField(default='', max_length=255)),
                ('totalTime', models.CharField(default='', max_length=50)),
                ('startTime', models.CharField(default='', max_length=50)),
                ('content', models.TextField()),
                ('case_num', models.IntegerField(null=True)),
                ('pass_num', models.IntegerField(null=True)),
                ('fail_num', models.IntegerField(null=True)),
                ('error_num', models.IntegerField(null=True)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.CharField(default='', max_length=30)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('sign_id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='sign',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.Sign'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Project'),
        ),
        migrations.AddField(
            model_name='interface',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Project'),
        ),
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Project'),
        ),
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Project'),
        ),
    ]
