# Generated by Django 2.0.3 on 2019-06-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_name', models.CharField(default='', max_length=255)),
                ('project_num', models.IntegerField(null=True)),
                ('env_num', models.IntegerField(null=True)),
                ('interface_num', models.IntegerField(null=True)),
                ('case_num', models.IntegerField(null=True)),
                ('plan_num', models.IntegerField(null=True)),
                ('sign_num', models.IntegerField(null=True)),
                ('report_num', models.IntegerField(null=True)),
                ('task_num', models.IntegerField(null=True)),
                ('qrcode_name', models.CharField(default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
